### ISSUE TITLE
experimental setup for exp34-epfl-soldiers tests

### ISSUE THREAD

**Issue by doug-leith** [DP-3T/bt-measurements#1]
Would it be possible to clarify the environment where the data in the exp34-epfl-soldiers tests was collected.  The README mentions a train, supermarket etc but it also says "This situation simulates an SBB 2nd class train compartment.”  which suggests the train data at least was not collected in an actual train.  The images in the computer-vision folder also suggest this (although its not clear what these images represent).  Were the tests carried out in an open space with a train carriage mocked up by arranging chairs and tables?  And similarly for the other tests?  Or was the data collected in an actual train, an actual supermarker, and actual club etc?  Thanks.

**Comment by gannimo** [comment]
Experiment 34 was conducted in the EPFL BC atrium, a 40m by 15m open space inside a large office building. The ground truth evaluation was done using a visual computing setup that mapped subjects to x/y coordinates on a grid. Such dynamic ground truth measurements are not reasonably possible in tight spaces and cumbersome to setup.

To validate these dynamic experiments we also conducted static experiments in real environments (e.g., in an actual tram) with similar results. We therefore are confident that our measurements hold up as conducted.

**Comment by pdehaye** [comment]
This would, for instance, have been the setup mocking a train (included because not readily visible to people, who would have to download and open the [zip file](https://github.com/DP-3T/bt-measurements/raw/master/exp34-epfl-soldiers/computer-vision/1_train.zip))

![ground_train_undist](https://user-images.githubusercontent.com/3274335/93005421-16174000-f551-11ea-8fed-412de56d6e1b.jpg)

**Comment by doug-leith** [comment]
Could you leave this issue open so that it remains visible on github and others can comment on it, thanks.

**Comment by doug-leith** [comment]
Would it be possible to also post the measurements taken on an actual tram/train and details of the setup, rather than just asserting that they agree with the mocked up tests.  Thanks.

**Comment by gannimo** [comment]
Thanks for the discussion. I added a note regarding the location/setup of the experiments in the corresponding README files. As the setup of past experiments will not change and given that the details about location are now included in the setup, I don't see a need to reopen the original issue.

@doug-leith , regarding other experiments, see issue #2 opened by @pdehaye.
