### ISSUE TITLE
Statistical treatment of the data

### ISSUE THREAD

**Issue by pdehaye** [DP-3T/bt-measurements#4]
I had a look in more details to the data, specifically the office and train data. Thanks to [@ s_______m______](https://twitter.com/s_______m______/status/1305228238231425025) on Twitter for getting started with some of the necessary work. 

I was very surprised at first to see the following jumps between 1.5m and 3m thresholds:
### train
![train_confusion_15](https://user-images.githubusercontent.com/3274335/93056801-3e945c80-f66d-11ea-80c0-1e35411f26cd.png)
![train_confusion_3](https://user-images.githubusercontent.com/3274335/93056796-3dfbc600-f66d-11ea-9dec-fc1000abdc2b.png)
### office
![office_confusion15](https://user-images.githubusercontent.com/3274335/93056909-608ddf00-f66d-11ea-9adb-95256df57642.png)
![office_confusion_3](https://user-images.githubusercontent.com/3274335/93056906-5ff54880-f66d-11ea-85ed-31ef599494b6.png)

In both cases it seems things go so much better with the 3m threshold than the 1.5m one, which is counter-intuitive. 
I then checked the histograms (train, then office):
![train_histogram](https://user-images.githubusercontent.com/3274335/93056802-3f2cf300-f66d-11ea-8fa4-3443adc2f521.png)
![office_histogram](https://user-images.githubusercontent.com/3274335/93056910-61267580-f66d-11ea-9035-32e77bd50a0d.png)

Of course it now makes sense: you can't misclassify many signals at range >3m if you don't take many such measurements. 

On the other hand, it is kind of alarming, for two different reasons:
* For the office situation, the number of people at distance `<=r` is expected to grow quadratically in `r` (for open floorplans). You are very much undersampling there.
* I prefer my public transport to be shaped in mostly one dimension, so the thinking is different there. What I was looking for was data that could be meaningfully compared to data in this [now-classic study](https://www.scss.tcd.ie/Doug.Leith/pubs/luas.pdf). They have shown very unexpected patterns in the strength of the Bluetooth signal as a function of distance (for instance, that the signal strength _increases_ with distance, sometimes). There is simply no space in the data you have collected to uncover this phenomenon. 

In the end, it looks like you just summed the sampled data for all scenarios to get a big dataset, that was then used to pick thresholds.

Have you checked what you were doing with a statistician?

**Comment by gannimo** [comment]
We aggregated the measurements from the different scenarios in experiment 34 for the PR curves. We looked into the effects of different distributions of distances and packet loss at distances and how this could change the precision / recall curves. We further looked into other uncertainties in distance calculation like those in phone calibration, phone position on the person, different materials in the environment etc. All of these considerations, including the feedback from the system and information from other researchers led to the determination of the thresholds.
